config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque'

  # Load balancer
  get '/check_alive' => 'main#check_alive'

  namespace :pigeon, defaults: { format: :json } do
    resources :mailings, only: [:show] do
      post :notify, on: :collection
      post :update, on: :member
      resources :contacts, only: :index
    end
  end

  namespace :ibis, defaults: { format: :json } do
    resources :options, only: %i(index create update destroy) do
      collection do
        post :dump
        get  :by_type
        get  :types
      end
    end

    resources :contacts, except: %i(new edit) do
      collection do
        get :count
      end
      member do
        get :letters
        get '/letters/:letter_id/details' => 'contacts#letter_details'
      end
    end

    resources :users, only: %i(index create show update destroy) do
      member do
        get :full
      end

      collection do
        get :count
        get :find_by_email
        get :search
        get :payment_conditions
      end
    end

    resources :mobile_users, only: %i(index create show update destroy) do
      collection do
        get :count
        get :search
      end
    end

    resources :orders, only: %i(index show create update) do
      get :count, on: :collection
    end

    resources :mailings, only: %i(index show create update count) do
      get :count, on: :collection
      get :preview, on: :collection
      member do
        get :contacts_count
        post :deliver_test
        post :build_template
        post :attach_contacts
        post :ready
        post :not_ready
      end
    end

    resources :reports, only: %i(index create)

    get '/import_news/'    => 'import_news#index'
    get '/import_news/:id' => 'import_news#show'
    post '/generate_flash' => 'newspaper#generate_flash'
    post '/dulton/upload'  => 'dulton#upload'

    scope :indexer do
      scope :users do
        get '/page/(:page)'     => 'indexer/users#page',  page:      /[0-9]+/
        get '/fresh/:timestamp' => 'indexer/users#fresh', timestamp: /[0-9]+/
      end

      scope :mobile_users do
        get '/page/(:page)'     => 'indexer/mobile_users#page',  page:      /[0-9]+/
        get '/fresh/:timestamp' => 'indexer/mobile_users#fresh', timestamp: /[0-9]+/
      end

      scope :orders do
        get '/page/(:page)'     => 'indexer/orders#page',  page:      /[0-9]+/
        get '/fresh/:timestamp' => 'indexer/orders#fresh', timestamp: /[0-9]+/
      end

      scope :payments do
        get '/page/(:page)'     => 'indexer/payments#page',  page:      /[0-9]+/
        get '/fresh/:timestamp' => 'indexer/payments#fresh', timestamp: /[0-9]+/
      end

      scope :contacts do
        get '/page/(:page)'     => 'indexer/contacts#page',  page:      /[0-9]+/
        get '/fresh/:timestamp' => 'indexer/contacts#fresh', timestamp: /[0-9]+/
      end
    end

    resources :products, only: %i(index show create update) do
      get :namespaces
      get :active_namespaces
      get :subproducts
      get :active_payment_kits
    end

    resources :namespaces, only: %i(index show create update) do
      get :payment_kits
      patch :set_base

      member do
        get :unsyncable_payment_kits
      end

      collection do
        get :unsyncable
      end
    end

    resources :subproducts, only: %i(show create update) do
      get :payment_kits
    end

    resources :periods,      only: %i(index show create update)
    resources :paymethods,   only: %i(index show create update)

    resources :payment_kits, only: %i(index show create update destroy) do
      get :associations
    end

    resources :cities, only: %i(index show create update destroy)

    resources :payments, only: %i(index show create update) do
      collection do
        get :statuses
        get :count
        get :export
        get 'subscribers_counts(/:year)(/:month)(/:day)(/:hours)(/:minutes)(/:seconds)' => 'payments#subscribers_counts', year: /\d{4,4}/, month: /0?[1-9]|1[0-2]/, day: /0?[1-9]|[1-2][0-9]|3[0-1]/, hours: /\d{1,2}/, minutes: /\d{1,2}/, seconds: /\d{1,2}/
      end
    end

    resources :redlines, only: %i(index show create update) do
      collection do
        get :count
      end
    end

    resources :people, except: [:new, :edit, :create, :destroy] do
      collection do
        get :synonyms
      end
    end
    
    namespace :mailing do
      resources :banners, only: %i(index show create update) do
        collection do
          get :count
        end
      end

      resources :mail_types, only: %i(index show create update)

      resources :stats, only: %i(links_clicks banners_clicks) do
        member do
          get :links_clicks
        end

        collection do
          get :banners_clicks
        end
      end

      resources :rules, only: %i(create update) do
        get :current, on: :collection
      end
    end
  end

  namespace :shark, defaults: { format: :json } do
    # password
    post '/sign_up_with_password' => 'users#sign_up_with_password'
    post '/sign_in_with_password' => 'users#sign_in_with_password'

    # oauth
    post '/sign_up_with_oauth' => 'users#sign_up_with_oauth'
    post '/sign_in_with_oauth' => 'users#sign_in_with_oauth'
    post '/create_social_account_link'  => 'users#create_social_account_link'
    post '/social_account_link_confirm' => 'users#confirm_social_account_link'

    # sessions
    get '/sessions/:token' => 'sessions#show', token: /[0-9a-f]+/
    delete '/sign_out' => 'users#sign_out'
    post '/confirm'    => 'users#confirm'
    post '/sessions'   => 'sessions#create'

    # user profile
    constraints(token: /[0-9a-f]+/) do
      get   '/users/:token'                      => 'users#show'
      get   '/users/:token/profile'              => 'users#profile'
      patch '/users/:token'                      => 'users#update'
      patch '/users/:token/password'             => 'users#change_password'
      patch '/users/:token/mailing'              => 'users#update_mailing'
      patch '/users/:token/accept_promo'         => 'users#accept_promo'
      put   '/users/:token/repeat_email_confirm' => 'users#repeat_email_confirm'
    end

    # password reset
    post '/send_password_reset_link'  => 'users#send_password_reset_link'
    get '/check_password_reset_token' => 'users#check_password_reset_token'
    post '/reset_password'            => 'users#reset_password'

    # feedback
    post '/feedback' => 'feedback#create'

    # subscriber
    get  '/contacts/:id'         => 'contacts#show'
    post '/contacts'             => 'contacts#create'
    post '/contacts/confirm'     => 'contacts#subscribe_confirm'
    post '/contacts/unsubscribe' => 'contacts#unsubscribe_confirm'
    get  '/contacts/unsubscribe/:unsubscribe_token' => 'contacts#unsubscribe_info', unsubscribe_token: /[a-zA-Z\d\-_=]+/

    # comments
    get   '/popular_comments/:widget_id/:xid' => 'comments#show_popular',   widget_id: /\d+/, xid: /\d+/
    patch '/popular_comments/:widget_id/:xid' => 'comments#update_popular', widget_id: /\d+/, xid: /\d+/

    scope :newspaper do
      # newspaper get archive url
      get '/:year/:month/:day/zip' => 'newspapers#zip', year: /\d{4}/, month: /\d{2}/, day: /\d{2}/
      # get '/last/zip'              => 'newspapers#zip'

      # newspaper generate archive
      get '/:year/:month/:day/generate_archive' => 'newspapers#generate_archive', year: /\d{4}/, month: /\d{2}/, day: /\d{2}/
      get '/last/generate_archive'              => 'newspapers#generate_archive'
    end

    namespace :orders do
      post '/card'          => 'card#create'
      post '/card/callback' => 'card#callback'
      get  '/card/check'    => 'card#check'

      post '/yandex'       => 'yandex#create'
      post '/yandex/check' => 'yandex#check'
      post '/yandex/aviso' => 'yandex#aviso'

      post '/apple'                   => 'apple#verify'
      post '/apple/link_subscription' => 'orders#link_subscription' # оставил для совместимости, потом можно будет удалить

      post '/google' => 'google#verify'

      post '/link_subscription' => 'orders#link_subscription'

      get  '/mobile_subscriptions/:target' => 'orders#mobile_subscriptions', target: /apple|google/
    end

    namespace :quotes do
      get :main_page
    end

    namespace :prices do
      get :active
    end

    namespace :redlines do
      get :active
    end

    namespace :mailing do
      get '/mail_types/:slug' => 'mail_types#show_by_slug', slug: /[a-z\d_]+/
    end
  end

  namespace :metynnis, defaults: { format: :json } do
    namespace :payments do
      post '/card' => 'card#create'
      get  '/card/check_transaction_id/:id' => 'card#check_transaction_id', id: /\d+/
      post '/card/callback' => 'card#callback'
      get  '/card/check_result/:id' => 'card#check_result', id: /\d+/

      post '/cash'  => 'cash#create'
      post '/trial' => 'trial#create'

      resource :paymaster, only: :create, controller: :pay_master do
        post :confirmation
        post :notification
      end

      namespace :yandex do
        resource :money,    controller: :yandex_money, only: :create
        resource :kassa,    controller: :yandex_kassa, only: :create
        resource :qiwi,     controller: :qiwi,         only: :create
        resource :web_money,controller: :web_money,    only: :create
        scope controller: :yandex_callback do
          post :check
          post :payment
          post :cancel
        end
      end

      constraints operator: /mts|megafon|beeline|tele2/ do
        post '/:operator'                        => 'mobile#create'
        post '/:operator/confirm'                => 'mobile#confirm'
        get  '/:operator/check/:subscription_id' => 'mobile#check'
        post '/:operator/callback'               => 'mobile#callback'
      end
      resources :subscribe_requests, only: [] do
        collection do
          post :company
          post :gift
        end

app/views/mailing_generators/newsrelease/_banner.html.slim
- if banner.type == 'picture'

  tr
    td width=15
    td colspan=4 align="center"
      a href="#{banner.url}" style='text-decoration: none;'
        img{
          src="#{Settings.hosts.cdn}#{banner.picture['url']}" 
          width="100%" 
          height="auto"
          style="display: block;"
          border=0}
    td width=15
        
- elsif banner.type == 'text'

  tr
    td width=15
    td colspan=4
      table border=1 bordercolor="#e3d1c7" cellpadding=0 cellspacing=0 width="100%" style="border-collapse: collapse;"
        tr
          td
            table border=0 width="100%" cellpadding=0 cellspacing=0 style="border-collapse: collapse;"
              tr
                td width=15
                td
                  br
                  a href="#{banner.url}" style='text-decoration: none; font-style: italic; font-weight: bold;'
                    font color="#857871" face="Georgia" size=4
                      b #{banner.title}
                  br
                  br
                  a href='#{banner.url}' style='text-decoration: none;'
                    font color="#857871" face="Arial" size=2 == banner.body
                  br
                  br
                  font color="#857871" face="Arial" size=2  Реклама
                  br
                  br
                td width=15
    td width=15
    
- elsif banner.type == 'embed'

  tr
    td width=15
    td colspan=4 align="center"
      == banner.embed
      / For testing
      / = render partial: 'mailing_generators/newsrelease/paywall'
    td width=15

app/views/mailing_generators/newsrelease/_body.html.slim
= render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 30, colspan: 6}
tr
  td width=15
  td colspan=4
    font color='#2e6f6f' face='Arial' size=4
      b #{page.title.mb_chars.upcase}
    hr color='#e3d1c7' size=1
  td width=15

= render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 5, colspan:6}

- page.documents.each_with_index do |document, index|
  - if 'front'== page.slug && index == 0
    tr valign='top'
      td width=15
      td width=170
        a href="#{full_url(document.url)}" style='text-decoration: none;'
          = image_with_dimension(document.image, :small, alt: document.title, image_class: nil)
      td width=15
        img src='http://www.vedomosti.ru/static/letter/padding.jpg' style='display: block;' border=0 width=15
      td colspan=2 valign='top' width='100%'
        a href="#{full_url(document.url)}" style='text-decoration: none'
          font color='#332f2e' face='Arial' size=4
            b #{document.title}
            - if document.pay_required?
              - if free
                img src='http://www.vedomosti.ru/static/letter/lock.png' style='padding-left: 10px'
              - else
                img src='http://www.vedomosti.ru/static/letter/unlock.png' style='padding-left: 10px'
        br
        font color='#544b48' face='Georgia' size=3 
          == document.subtitle
      td width=15

  - else
    tr valign='top'
      td width=15
      td colspan=4
        a href="#{full_url(document.url)}" style='text-decoration: none;'
          font color='#332f2e' face='Arial' size=4
            b #{document.title}
            - if document.pay_required?
              - if free
                img src='http://www.vedomosti.ru/static/letter/lock.png' style='padding-left: 10px'
              - else
                img src='http://www.vedomosti.ru/static/letter/unlock.png' style='padding-left: 10px'
        br
        font color='#544b48' face='Georgia' size=3 
          == document.subtitle
      td width=15
  - if index != page.documents.size - 1
    = render partial: 'mailing_generators/newsrelease/dividers/page', locals: {height: 30}

- if page_counter == 2 && banner_position
  = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 55, colspan: 6}
  
  /!
    banner:#{banner_position}

app/views/mailing_generators/newsrelease/_footer.html.slim
tr#footer valign="top"
  td width=15
  td colspan=4 valign='middle'
    table border=0 width="100%" colspan=0 rowspan=0 style='border-collapse: collapse;'
      tr
        td valign='middle' height=10
          hr color='#e3d1c7' size=1
      tr
        td
          font color='#857871' face='Arial' size=2 Вы получили это сообщение, так как подписались на рассылку «Ведомостей».
      tr
        td
          font color='#857871' face='Arial' size=2 #{"Если вы хотите отписаться, "}
          <a href='{{data_escape "unsubscribe"}}' style="text-decoration: underline;" target='_blank'>
            <font color="#857871" face="Arial" size="2">перейдите по ссылке</font>
          </a>
      tr
        td
          font color='#857871' face='Arial' size='2' #{"Обратная связь: "}
          a href='mailto:new-vedomosti@vedomosti.ru' target='_blank' style="text-decoration: underline;"
            font color='#857871' face='Arial' size=2 new-vedomosti@vedomosti.ru
      tr
        td valign='middle' height=10
          hr color='#e3d1c7' size=1
    table cospan=0 rowspan=0 border=0 style='border-collapse: collapse;'
      tr
        td
          font color='#857871' face='Arial' size=2 #{"«Ведомости» в соцсетях:"}
        td
          | &nbsp;&nbsp;
          a href='http://www.facebook.com/Vedomosti' target='_blank'
            img alt='facebook' border=0 src='http://www.vedomosti.ru/static/letter/icon1.jpg'
          | &nbsp;&nbsp;
          a href='http://twitter.com/vedomosti' target='_blank'
            img alt='twitter' border=0 src='http://www.vedomosti.ru/static/letter/icon2.jpg'
          | &nbsp;&nbsp;
          a href='http://vk.com/vedomosti' target='_blank'
            img alt='vk' border=0 src='http://www.vedomosti.ru/static/letter/icon3.jpg'
    font color='#857871' face='Arial' size='2'  Все права защищены © АО Бизнес Ньюс Медиа, 1999 – #{Time.now.year}
    br
    br
    br
    br
  td width=15

app/views/mailing_generators/newsrelease/_header.html.slim
tr#info
  td width=15
  td align='center' colspan=4
    p
      font color='#88807a' face='Georgia' size=3 style="font-style: italic;"
        | Рассылка для подписчиков
  td width=15

tr#header
  td width=15
    img src='http://www.vedomosti.ru/static/letter/padding.jpg' style='display: block;' border=0 width=15
  td align='center' colspan=4 height=106
    a href='http://www.vedomosti.ru/' target='_blank'
      img alt='Ведомости' border=0 width=376 height=106 src='http://www.vedomosti.ru/static/letter/logo.jpg' style='display: block;'
  td width=15
    img src='http://www.vedomosti.ru/static/letter/padding.jpg' style='display: block;' border=0 width=15

tr align='center'
  td colspan=6 height=70 valign='bottom'
    a href="#{full_url(@newsrelease.url)}" target='_blank'
      img alt='подписаться' border=0 src='http://www.vedomosti.ru/static/letter/newspaper.jpg' style='display: block;'

app/views/mailing_generators/newsrelease/_header_free.html.slim
tr#info
  td width=15
  td align='center' colspan=4
    img border=0 src='http://www.vedomosti.ru/static/letter/warning.png' style="vertical-align: bottom;"
    | &nbsp;&nbsp;
    font color='#88807a' face='Georgia' size=3 style="font-style: italic;"
      | Полная версия материалов доступна подписчикам «Ведомостей». Подписаться вы можете
      | &nbsp;
      a href="http://buy.vedomosti.ru/" target='_blank' style="text-decoration: underline; color: #2e6f6f;" здесь
    br
    br
    br

  td width=15

tr#header
  td width=15
    img src='http://www.vedomosti.ru/static/letter/padding.jpg' style='display: block;' border=0 width=15
  td align='center' colspan=4 height=106
    a href='http://www.vedomosti.ru/' target='_blank'
      img alt='Ведомости' border=0 width=376 height=106 src='http://www.vedomosti.ru/static/letter/logo.jpg' style='display: block;'
  td width=15
    img src='http://www.vedomosti.ru/static/letter/padding.jpg' style='display: block;' border=0 width=15
  
/ tr#date align='center'
/   td width=15
/   td colspan=4
/     font color='#88807a' face='Georgia' size=3
/       i #{Russian::strftime(@newsrelease.published_at, "%A, %d %B")}
/   td width=15
/     img src='http://www.vedomosti.ru/static/letter/padding.jpg' style='display: block;' border=0

app/views/mailing_generators/newsrelease/_newsrelease.html.slim
doctype html
html
  head
    meta content="text/html; charset=utf-8" http-equiv="Content-Type"
    title "#{@newsrelease.title} от #{@newsrelease.published_at.strftime('%d.%m.%Y')}"

    css:
      a {
        text-decoration: none;
      }
    
      div, p, a, li, td {
        -webkit-text-size-adjust: none;
      }

      @media only screen and (max-width: 480px) {
        table[class='body']{width: 320px!important}
      }

      @font-face {
        font-family: 'RobotoLight';
        font-style: normal;
        font-weight: normal;
        src: url(https://cdn.vedomosti.ru/assets/RobotoSlab-Light-webfont.woff) format('woff');
      }
      
      @font-face {
        font-family: 'RobotoRegular';
        font-style: normal;
        font-weight: normal;
        src: url(https://cdn.vedomosti.ru/assets/RobotoSlab-Regular-webfont.woff) format('woff');
      }
      
  body
    table.wrapper bgcolor="#e3d1c7" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;"
      tr
        td height="45"
          span style='display:none !important; visibility:hidden; opacity:0; color:transparent; height:0; width:0;'
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].title}
            br
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].subtitle}

      tr align="center"
        td
          table.body bgcolor="#fff6f1" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;"

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 15, colspan: 6}

            /!
              banner:10

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 30, colspan: 6}

            = render 'mailing_generators/newsrelease/header'

            = render partial: 'mailing_generators/newsrelease/body', collection: @pages, as: :page, locals: {banner_position: 20, free: false}

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 50, colspan: 6}

            = render partial: 'mailing_generators/newsrelease/ad/companies'

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 25, colspan: 6}

            = render partial: 'mailing_generators/newsrelease/ad/application'

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 3, colspan: 6}

            = render 'mailing_generators/newsrelease/footer'
            
      tr
        td height="45"
          span style='display:none !important; visibility:hidden; opacity:0; color:transparent; height:0; width:0;'
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].title}
            br
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].subtitle}

app/views/mailing_generators/newsrelease/_newsrelease_free.html.slim
doctype html
html
  head
    meta content="text/html; charset=utf-8" http-equiv="Content-Type"
    title "#{@newsrelease.title} от #{@newsrelease.published_at.strftime('%d.%m.%Y')}"

    css:
      a {
        text-decoration: none;
      }
    
      div, p, a, li, td {
        -webkit-text-size-adjust: none;
      }

      @media only screen and (max-width: 480px) {
        table[class='body']{width: 320px!important}
      }
      
      @font-face {
        font-family: 'RobotoLight';
        font-style: normal;
        font-weight: normal;
        src: url(https://cdn.vedomosti.ru/assets/RobotoSlab-Light-webfont.woff) format('woff');
      }

      @font-face {
        font-family: 'RobotoRegular';
        font-style: normal;
        font-weight: normal;
        src: url(https://cdn.vedomosti.ru/assets/RobotoSlab-Regular-webfont.woff) format('woff');
      }

  body
    table.wrapper bgcolor="#e3d1c7" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;"
      tr
        td height="45"
          span style='display:none !important; visibility:hidden; opacity:0; color:transparent; height:0; width:0;'
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].title}
            br
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].subtitle}

      tr align="center"
        td
          table.body bgcolor="#fff6f1" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;"

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 15, colspan: 6}

            /!
              banner:110

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 30, colspan: 6}

            = render 'mailing_generators/newsrelease/header_free'

            = render partial: 'mailing_generators/newsrelease/body', collection: @pages, as: :page, locals: {banner_position: false, free: true }

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 55, colspan: 6}
            
            /!
              banner:100

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 30, colspan: 6}

            /!
              banner:120
                
            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 50, colspan: 6}

            = render partial: 'mailing_generators/newsrelease/ad/companies'

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 25, colspan: 6}

            = render partial: 'mailing_generators/newsrelease/ad/application'

            = render partial: 'mailing_generators/newsrelease/dividers/default', locals: {height: 3, colspan: 6}

            = render 'mailing_generators/newsrelease/footer'
            
      tr
        td height="45"
          span style='display:none !important; visibility:hidden; opacity:0; color:transparent; height:0; width:0;'
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].title}
            br
            font size=0 color='#e3d1c7' #{@pages[0].documents[0].subtitle}

app/views/mailing_generators/newsrelease/_paywall.html.slim
table border=1 bordercolor="#e3d1c7" cellpadding=0 cellspacing=0 width="328" height="118" style="background-color: #fff; border-radius: 20px;"

  tr height="75px"
    td width="35%" align="center" valign="bottom" bgcolor="#fff" style="border: none; border-radius: 20px 0 0 0;"
      del style="color: #332f2e; font-family: 'RobotoRegular', Arial; font-size: 30px;"
        | 9420
    td width="65%" align="left" valign="bottom" bgcolor="#fff" style="border: none; border-radius: 0 20px 0 0;"
      span style="color: #cc3333; font-family: 'RobotoLight', Arial; font-size: 48px;"
        | 4920
      span style="color: #cc3333; font-family: 'RobotoLight', Arial; font-size: 20px;"
        | руб.
        
  tr height="45px"
    td width="35%" align="center" valign="top" bgcolor="#fff" style="border: none; border-radius: 0 0 0 20px;"
    td width="65%" align="left" valign="top" bgcolor="#fff" style="border: none; border-radius: 0 0 20px 0;"
      span style="color: #857871; font-family: 'RobotoRegular', Arial; font-size: 18px;" 12 месяцев

p{style="text-align: center; font-family: Arial; font-size: 16px; color: #332f2e;"}
  | Подпишитесь, чтобы получить полный доступ к свежему номеру и читать "ведомости" без ограничений
	
table cellpadding=0 cellspacing=0 width="328" height="50"
  tr
    td bgcolor="#2e6f6f" align="center" style="border: 1px solid #2e6f6f; border-bottom: 5px solid #255959;"
      a href="#" style="text-decoration: none; font-weight: bold; text-align: center; color: #fff; width: 100%; height: 45px; line-height: 45px; display: inline-block;"
        span style="font-size: 18px; font-family: Arial;"
          | Подписаться